### ISSUE TITLE
aclocal & automake 1.15 => 1.16

### ISSUE THREAD

**Issue by nsteinmetz** [dymosoftware/Drivers#4]
Hi there,

Trying to compile drivers on my RPI3 on updated version of rasbian (bullseye)

In `Makefile`, I had to change:

```
# Line 221
ACLOCAL = aclocal-1.16

# Line 226
AUTMAKE = automake-1.16
```

Regards,

**Comment by LawrenceK** [comment]
try
aclocal
automake
./configure
make

Also needed libboost-dev
And in src/lm/LabelManagerLanguageMonitorV2.cpp missing #include <ctime>

**Comment by nsteinmetz** [comment]
Thanks, it worked this way.
